name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy-iac:
    runs-on: [self-hosted, terraform]

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------------
      # AWS authentication (OIDC)
      # ------------------------------
      # - name: Configure AWS Credentials using OIDC
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
      #     role-session-name: github-terraform-session

      # ------------------------------
      # Terraform Setup
      # ------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Install tfsec for security scanning
        run: |
          curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.11/tfsec-linux-amd64
          chmod +x tfsec
          ./tfsec --version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Run tfsec Scan
        run: ./tfsec . || true

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # ------------------------------
      # Install kubectl AFTER cluster is ready
      # ------------------------------
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      # ------------------------------
      # Authenticate kubectl to EKS
      # MUST RUN AFTER TERRAFORM APPLY
      # ------------------------------
      - name: Authenticate kubectl with EKS
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      # ------------------------------
      # Deploy ClusterIssuer AFTER cert-manager installation
      # ------------------------------
      - name: Deploy ClusterIssuer
        run: kubectl apply -f ClusterIssuer.yaml

      # ------------------------------
      # Deploy ArgoCD ingress
      # ------------------------------
      - name: Deploy ArgoCD Ingress
        run: kubectl apply -f ingress-argocd.yaml -n argocd


      #- name: Terraform Destroy
      #  run: terraform destroy -auto-approve